// Maps ESPN team display names to your DB team names
// Shared between /api/update-results and /api/live-scores
export const ESPN_NAME_MAP: Record<string, string> = {
  'Mexico': 'Mexico',
  'South Africa': 'South Africa',
  'South Korea': 'South Korea',
  'Korea Republic': 'South Korea',
  'Czech Republic': 'Czechia',
  'Canada': 'Canada',
  'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
  'Qatar': 'Qatar',
  'Switzerland': 'Switzerland',
  'Brazil': 'Brazil',
  'Morocco': 'Morocco',
  'Haiti': 'Haiti',
  'Scotland': 'Scotland',
  'United States': 'United States',
  'USA': 'United States',
  'Paraguay': 'Paraguay',
  'Australia': 'Australia',
  'Turkey': 'Turkey',
  'Türkiye': 'Turkey',
  'Germany': 'Germany',
  'Curacao': 'Curacao',
  'Curaçao': 'Curacao',
  'Netherlands': 'Netherlands',
  'Japan': 'Japan',
  'Ivory Coast': 'Ivory Coast',
  "Côte d'Ivoire": 'Ivory Coast',
  'Ecuador': 'Ecuador',
  'Sweden': 'Sweden',
  'Tunisia': 'Tunisia',
  'Spain': 'Spain',
  'Cape Verde': 'Cape Verde',
  'Belgium': 'Belgium',
  'Egypt': 'Egypt',
  'Saudi Arabia': 'Saudi Arabia',
  'Uruguay': 'Uruguay',
  'Iran': 'Iran',
  'IR Iran': 'Iran',
  'New Zealand': 'New Zealand',
  'France': 'France',
  'Senegal': 'Senegal',
  'Iraq': 'Iraq',
  'Norway': 'Norway',
  'Argentina': 'Argentina',
  'Algeria': 'Algeria',
  'Austria': 'Austria',
  'Jordan': 'Jordan',
  'Portugal': 'Portugal',
  'DR Congo': 'DR Congo',
  'Congo DR': 'DR Congo',
  'Uzbekistan': 'Uzbekistan',
  'Colombia': 'Colombia',
  'England': 'England',
  'Croatia': 'Croatia',
  'Ghana': 'Ghana',
  'Panama': 'Panama',
}